# Generated by Django 5.2 on 2025-05-06 00:47

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to=courses.models.upload_image)),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email_required', 'Email required')], default='any', max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pub', 'Published'), ('soon', 'Coming soon')], default='draft', max_length=25)),
            ],
        ),
    ]
