# Generated by Django 5.2 on 2025-05-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('email', 'Email required')], default='email', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pub', 'Published'), ('soon', 'Coming soon')], default='draft', max_length=5),
        ),
    ]
