# Generated by Django 5.2 on 2025-05-06 01:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_access_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='images',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
