# Generated by Django 5.2 on 2025-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.BooleanField(default=False, help_text="if user doesn't have access to course, can they see this ?"),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pub', 'Published'), ('soon', 'Coming soon')], default='pub', max_length=10),
        ),
    ]
